# Generated by Django 5.2.4 on 2025-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.FileField(
                        error_messages={
                            "max_length": "File name must be shorter!",
                            "required": "File attachment required",
                        },
                        upload_to="images",
                    ),
                ),
            ],
        ),
    ]
