# Generated by Django 5.2.4 on 2025-08-12 10:56

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_userprofile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile",
            field=models.ImageField(
                error_messages={
                    "max_length": "File name must be shorter!",
                    "required": "File attachment required",
                },
                upload_to="images",
                validators=[profiles.models.file_size],
            ),
        ),
    ]
