# Generated by Django 5.2.4 on 2025-08-09 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="email",
            field=models.EmailField(
                error_messages={
                    "invalid": "Enter a valid email address",
                    "required": "Email is required",
                },
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="full_name",
            field=models.CharField(
                error_messages={
                    "max_length": "Please enter a shorter name!",
                    "min_length": "Please enter a valid name",
                    "required": "Your name must not be empty!",
                },
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="message",
            field=models.TextField(
                error_messages={
                    "max_length": "Please give a short feedback message!",
                    "min_length": "Please give valid feedback message",
                    "required": "Feedback message must not be empty!",
                },
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                error_messages={
                    "max_value": "Please rate correctly (1 to 5)!",
                    "min_value": "Please rate correctly (1 to 5)!",
                    "required": "Rating is required",
                },
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
